### PR TITLE
Filter catalog page

### PR DESCRIPTION
**Pull request by MrBaiame**

### CODE REVIEW

**Comment by marionf** [comment]
@MrBaiame 

2 issues:
- When I select a category, "Categories" is still displayed instead of the name of the category selected
- When I select a category and enter something in the search bar, it should search and display results of modules that are only in the selected category

capture d ecran_355

It works on the core: 

capture d ecran_354

**Comment by marionf** [comment]
@MrBaiame 

When I select "Other" category, I have no results.
I should have 6

capture d ecran_356

**Comment by MrBaiame** [comment]
Should be fixed now, ping @marionf

**Comment by PierreRambaud** [comment]
Thanks @MrBaiame

**Pull request merged**
