### PR TITLE
Make MBO handle adding the Recommended modules button in pages

### PR DESCRIPTION
**Pull request by eternoendless**
This PR makes MBO handle adding the "Recommended modules and services" button in all pages. An exception list has been added to prevent adding this button in pages where we don't want it to (all module controllers and module-related pages).

This change paves the way to remove this behavior from the core. Backwards compatibility is assured by removing the previous, core-added buttons before adding the new ones.

Since the core does not support letting module developers choose where in the toolbar they want to add their buttons (it only supports adding at the start of the toolbar), I chose to handle everything using Javascript. This means that a small script is loaded on ALL BackOffice pages, but it shouldn't be a problem once it's stored in cache.

The button is now added just before the Help button, or at the end of the toolbar if that button is not there.

### CODE REVIEW

**Comment by marionf** [comment]
In a multistore context, I have 2 buttons on legacy pages

capture d ecran_1150

capture d ecran_1151

On symfony pages it's ok, I have only one button with the good link to controller=AdminPsMboModule

On some pages (like states for example) there wasn't the recommanded button before.
With this PR the button appear

capture d ecran_1152

And no modules are displayed when I click on it

capture d ecran_1153

**Comment by eternoendless** [comment]
> On some pages (like states for example) there wasn't the recommanded button before.
With this PR the button appear (...) And no modules are displayed when I click on it

That's normal! The current behavior is to make the button appear only if there are recommended modules for that specific page. However, this requires the list to be downloaded before the page is displayed. This is one of the reasons the BO takes so long to load the first time you log in every day (because the cache is renewed every 24h).

This PR changes that behavior in order to delay that download until _after_ the user has clicked that button. But that also means we cannot know beforehand if there are elements to show or not, so I chose to always show the button.

**Comment by eternoendless** [comment]
All other bugs have been fixed :)

**Comment by marionf** [comment]
Thank you @eternoendless it's all good

**Comment by LouToma** [comment]
@eternoendless 
"This PR makes MBO handle adding the "Recommended modules and services" button in all pages. An exception list has been added to prevent adding this button in pages where we don't want it to (all module controllers and module-related pages)."
Can I have examples to test on specific pages ?
Thanks.

**Comment by eternoendless** [comment]
Examples of pages where you **shouldn't** see the button:

- MBO pages (and their Core counterparts)
- Module Manager
- Add/edit language (sf page)
- Add/edit URL (sf page)
- Add/edit category (sf page)
- Add/edit customer (sf page)

**Comment by LouToma** [comment]
All good for me, thanks !

**Comment by PierreRambaud** [comment]
Thanks everyone!

**Pull request merged**
